Repository ritika728/Wellness_Wave, pull requests merged in 2024-02, with the labels that each got.

#154 [BUG] Tracking page issue fixed #135
  css_files/home.css
Labels: JWOC, easy

#158 Fixed the color of all calculator boxes in Tracking section
  css_files/fitnesstracking.css
  html_files/fitnesstracking.html
Labels: JWOC, easy

#160 add blog page to show blog related to health #152
  css_files/blog.css
  enroll/index.html
  html_files/blog.html
  html_files/feedback.html
  html_files/fitnesstracking.html
  html_files/wellness.html
  images/Blog/Blog 1.jpg
  images/Blog/Blog 2.jpg
  images/Blog/Blog 3.jpg
  images/Blog/Blog 4.jpg
  images/Blog/Blog 5.jpg
  images/Blog/Blog 6.jpg
  images/wellness-images/Blog 1.jpg
  images/wellness-images/Blog 2.jpg
  images/wellness-images/Blog 3.jpg
  images/wellness-images/Blog 4.jpg
  images/wellness-images/Blog 5.jpg
  images/wellness-images/Blog 6.jpg
  index.html
Labels: JWOC, hard

#162 [BUG] Absence of navbar in all calculator #161
  html_files/bac.html
  html_files/bloodpressure.html
  html_files/bmi.html
  html_files/bmr.html
  html_files/body_fat.html
  html_files/breastcancer.html
  html_files/calorie.html
  html_files/dri.html
  html_files/due_date.html
  html_files/heart_rate.html
  html_files/ideal_weight.html
  html_files/leanmass.html
  html_files/pace.html
  html_files/prot_intake.html
  html_files/sleep.html
  html_files/water_intake.html
Labels: JWOC, medium

#165 Added Animations To Tracking Page
  html_files/fitnesstracking.html
Labels: JWOC, medium

#168 Depression Screening Test Calculator
  css_files/depression.css
  html_files/depression.html
  html_files/fitnesstracking.html
  images/depression.jpeg
  javascript/depression.js
Labels: JWOC, medium

#169 editted the css of tracking section calculators
  css_files/bmi.css
  css_files/body_fat.css
  css_files/prot.css
Labels: JWOC, easy

#171 Add Life Expectancy Calculator
  css_files/lifeexpectancy.css
  html_files/fitnesstracking.html
  html_files/lifeexpectancy.html
  images/lifeexpectancy.jpeg
  javascript/lifeexpectancy.js
Labels: JWOC, medium

#174 Improved the Hamburger
  css_files/hambg.css
  css_files/navbar.css
  enroll/index.html
  html_files/bac.html
  html_files/blog.html
  html_files/bloodpressure.html
  html_files/bmi.html
  html_files/bmr.html
  html_files/body_fat.html
  html_files/breastcancer.html
  html_files/calc.html
  html_files/calorie.html
  html_files/dri.html
  html_files/due_date.html
  html_files/faq.html
  html_files/feedback.html
  html_files/fitnesstracking.html
  html_files/heart_rate.html
  html_files/ideal_weight.html
  html_files/leanmass.html
  html_files/pace.html
  html_files/prot_intake.html
  html_files/sleep.html
  html_files/water_intake.html
  html_files/wellness.html
  index.html
  javascript/hambg.js
Labels: JWOC, medium

#179 Customized Scrollbar
  css_files/home.css
  enroll/index.html
  html_files/blog.html
  html_files/faq.html
  html_files/feedback.html
  html_files/fitnesstracking.html
  html_files/wellness.html
  index.html
  javascript/hambg.js
  javascript/index.js
Labels: JWOC, medium

#180 Fixed Wellness Wave Navigation
  enroll/index.html
  html_files/Emotional_health.html
  html_files/Social_Well_Bieng.html
  html_files/bac.html
  html_files/blog.html
  html_files/bloodpressure.html
  html_files/bmi.html
  html_files/bmr.html
  html_files/body_fat.html
  html_files/breastcancer.html
  html_files/calorie.html
  html_files/depression.html
  html_files/diet.html
  html_files/dri.html
  html_files/due_date.html
  html_files/faq.html
  html_files/feedback.html
  html_files/fitnesstracking.html
  html_files/heart_rate.html
  html_files/ideal_weight.html
  html_files/leanmass.html
  html_files/lifeexpectancy.html
  html_files/mental_health.html
  html_files/pace.html
  html_files/physical_health.html
  html_files/prot_intake.html
  html_files/sleep.html
  html_files/spiritual_wellness.html
  html_files/water_intake.html
  html_files/wellness.html
  index.html
Labels: JWOC, easy

#181 Fixed UI of Tracking Page
  html_files/fitnesstracking.html
Labels: JWOC, easy

#184 Add a light and dark mode button . #74
  css_files/faq.css
  css_files/feedback.css
  css_files/mode.css
  enroll/index.html
  enroll/style.css
  html_files/blog.html
  html_files/faq.html
  html_files/feedback.html
  html_files/fitnesstracking.html
  html_files/wellness.html
  index.html
Labels: JWOC, medium

#185 Improve the Footer
  css_files/footer.css
  enroll/index.html
  html_files/Emotional_health.html
  html_files/Social_Well_Bieng.html
  html_files/bac.html
  html_files/blog.html
  html_files/bloodpressure.html
  html_files/bmi.html
  html_files/bmr.html
  html_files/body_fat.html
  html_files/breastcancer.html
  html_files/calc.html
  html_files/calorie.html
  html_files/depression.html
  html_files/diet.html
  html_files/dri.html
  html_files/due_date.html
  html_files/faq.html
  html_files/feedback.html
  html_files/fitnesstracking.html
  html_files/heart_rate.html
  html_files/ideal_weight.html
  html_files/leanmass.html
  html_files/lifeexpectancy.html
  html_files/mental_health.html
  html_files/pace.html
  html_files/physical_health.html
  html_files/prot_intake.html
  html_files/sleep.html
  html_files/spiritual_wellness.html
  html_files/water_intake.html
  html_files/wellness.html
  index.html
Labels: JWOC, hard

#189 Replace all old Navbar & Improve UI
  html_files/Emotional_health.html
  html_files/Social_Well_Bieng.html
  html_files/depression.html
  html_files/diet.html
  html_files/lifeexpectancy.html
  html_files/mental_health.html
  html_files/physical_health.html
  html_files/spiritual_wellness.html
  index.html
Labels: JWOC, medium
