Repository ritika728/Wellness_Wave, pull requests merged in 2024-01, with the labels that each got.

#25 Added favicons
  html_files/bmi.html
  html_files/calorie.html
  html_files/fitnesstracking.html
  html_files/mental_health.html
  html_files/physical_health.html
  html_files/sleep.html
  html_files/wellness.html
  images/wave (1).png
  index.html
Labels: JWOC, easy

#27 Calculators alignment for consistency
  css_files/fitnesstracking.css
  html_files/fitnesstracking.html
Labels: JWOC, easy

#29 Contact Us section
  css_files/home.css
  images/flat-design-illustration-customer-support_23-2148887720.avif
  index.html
  javascript/index.js
Labels: JWOC, medium

#30 Add: Faq page
  css_files/faq.css
  html_files/bmi.html
  html_files/calorie.html
  html_files/faq.html
  html_files/fitnesstracking.html
  html_files/mental_health.html
  html_files/physical_health.html
  html_files/sleep.html
  html_files/spiritual_wellness.html
  html_files/wellness.html
  index.html
  javascript/faq.js
Labels: JWOC, medium

#31 footer
  .vscode/settings.json
  Wellness Wave.html
  css_files/icon.css
  html_files/bmi.html
  html_files/calorie.html
  html_files/fitnesstracking.html
  html_files/mental_health.html
  html_files/physical_health.html
  html_files/sleep.html
  html_files/terms.html
  html_files/wellness.html
  index.html
Labels: JWOC, medium

#43 improve What's In It UI
  css_files/home.css
Labels: JWOC, easy

#44 Fix Issue 33
  css_files/watintake.css
  html_files/fitnesstracking.html
  html_files/water_intake.html
  javascript/water_intake.js
Labels: JWOC, medium

#46 Elaborate Emotional and Social_Well_Bieng section
  css_files/Emotional_Health.css
  css_files/Social_Well_Bieng.css
  html_files/Emotional_health.html
  html_files/Social_Well_Bieng.html
  html_files/wellness.html
  images/ImageForArticle_22647_16545264138148394.webp
  images/friendship.jpg
Labels: JWOC, medium

#49 Go to top button added
  css_files/home.css
  css_files/workout.css
  html_files/faq.html
  html_files/fitnesstracking.html
  html_files/mental_health.html
  html_files/physical_health.html
  html_files/spiritual_wellness.html
  html_files/wellness.html
  html_files/workout.html
  index.html
  javascript/faq.js
  javascript/index.js
Labels: JWOC, medium

#45 Freshcal
  css_files/calci.css
  css_files/home.css
  html_files/bmi.html
  html_files/body_fat.html
  html_files/calorie.html
  html_files/faq.html
  html_files/fitnesstracking.html
  html_files/sleep.html
  html_files/spiritual_wellness.html
  html_files/terms.html
  html_files/water_intake.html
  html_files/wellness.html
  index.html
  javascript/body_fat.js
  javascript/faq.js
  javascript/water_intake.js
Labels: JWOC, hard

#54 Added Ideal Weight Calculator and fixed the bug in faq section
  css_files/ideal_weight.css
  html_files/fitnesstracking.html
  html_files/ideal_weight.html
  index.html
  javascript/ideal_weight.js
Labels: JWOC, medium

#62 Contact Section Working
  css_files/home.css
  html_files/Emotional_health.html
  html_files/Social_Well_Bieng.html
  html_files/bmi.html
  html_files/body_fat.html
  html_files/calorie.html
  html_files/faq.html
  html_files/fitnesstracking.html
  html_files/mental_health.html
  html_files/physical_health.html
  html_files/sleep.html
  html_files/spiritual_wellness.html
  html_files/water_intake.html
  html_files/wellness.html
  index.html
Labels: JWOC, easy

#48 Physical UI update
  css_files/physical_health.css
  html_files/physical_health.html
  images/physical-bg5.jpg
Labels: JWOC, easy

#63 FIX: Update scrollbar
  css_files/home.css
Labels: JWOC, easy

#66 UI of calculators improved
  css_files/bmi.css
  css_files/body_fat.css
  css_files/calorie.css
  css_files/ideal_weight.css
  css_files/sleep.css
  css_files/water_intake.css
  html_files/bmi.html
  html_files/body_fat.html
  html_files/calorie.html
  html_files/sleep.html
  html_files/water_intake.html
  images/bmi.jpg
  images/calorie.jpg
  images/fat.jpg
  images/sleep.jpg
  images/water.jpg
  images/weight.jpg
  images/weight.webp
Labels: JWOC, easy

#69 Calculator box aligned
  css_files/fitnesstracking.css
Labels: JWOC, easy

#78 calorie calculator description added
  html_files/fitnesstracking.html
Labels: JWOC, easy

#79 Created a nutrition page and linked all sections with their respective pages
  css_files/home.css
  html_files/diet.html
  images/diet_img.jpg
  index.html
Labels: JWOC, medium

#85 Fitness UI update
  css_files/fitnesstracking.css
  css_files/home.css
  html_files/Social_Well_Bieng.html
  html_files/fitnesstracking.html
  html_files/mental_health.html
  html_files/physical_health.html
  javascript/faq.js
Labels: JWOC, easy

#83 Blood Pressure Calculation
  css_files/bloodpressure.css
  html_files/bloodpressure.html
  html_files/fitnesstracking.html
  images/blood_pressure.png
  javascript/bloodpressure.js
Labels: JWOC, medium

#87 made the changes
  css_files/feedback.css
  html_files/Emotional_health.html
  html_files/Social_Well_Bieng.html
  html_files/bmi.html
  html_files/body_fat.html
  html_files/calorie.html
  html_files/faq.html
  html_files/feedback.html
  html_files/fitnesstracking.html
  html_files/ideal_weight.html
  html_files/mental_health.html
  html_files/physical_health.html
  html_files/sleep.html
  html_files/spiritual_wellness.html
  html_files/water_intake.html
  html_files/wellness.html
  index.html
Labels: JWOC, medium

#89 Heart rate calculator
  css_files/heart_rate.css
  css_files/home.css
  html_files/fitnesstracking.html
  html_files/heart_rate.html
  images/heart_rate1.jpg
  javascript/heart_rate.js
Labels: JWOC, medium

#94 Added BMR Calculator
  css_files/bmr.css
  html_files/bmr.html
  html_files/fitnesstracking.html
  html_files/innnn.html
  images/bmr.png
  javascript/bmr.js
Labels: JWOC, medium

#99 Added Pregnancy Due Date Calculator
  css_files/due_date.css
  html_files/due_date.html
  html_files/fitnesstracking.html
  images/due_date1.jpg
  javascript/due_date.js
Labels: JWOC, medium

#96 Added Figma Link
  figma_file/figma.txt
Labels: JWOC, hard

#105 wellness section UI : use cards with different styles Updated(#43)
  css_files/home.css
  css_files/wellness.css
  html_files/wellness.html
  images/wellness-images/30-day-challenge.webp
  images/wellness-images/e.jpg
  images/wellness-images/mental.png.jpg
  images/wellness-images/physical-health.png.jpg
  images/wellness-images/social.jpg
  images/wellness-images/spiritual.avif
Labels: JWOC, medium

#101 Hamburger-Lvl1 added needed more enhancements
  css_files/faq.css
  css_files/feedback.css
  css_files/fitnesstracking.css
  css_files/hambg.css
  css_files/home.css
  css_files/wellness.css
  html_files/faq.html
  html_files/feedback.html
  html_files/fitnesstracking.html
  html_files/wellness.html
  index.html
  javascript/hambg.js
Labels: JWOC, easy

#112 Styling of Sleep Calculator page
  css_files/sleep.css
  html_files/sleep.html
Labels: JWOC, easy

#110 Added DRI Calculator
  css_files/dri.css
  html_files/dri.html
  html_files/fitnesstracking.html
  images/dri.jpg
  javascript/dri.js
Labels: JWOC, medium

#116 footer fixed fixes issue #114
  css_files/home.css
  css_files/sleep.css
Labels: JWOC, easy

#118 Created a Protein Intake Calculator
  css_files/home.css
  css_files/prot.css
  html_files/fitnesstracking.html
  html_files/ideal_weight.html
  html_files/prot_intake.html
  images/wellness-images/image.jpg
Labels: JWOC, medium

#119 added pace calculator
  css_files/pace.css
  html_files/fitnesstracking.html
  html_files/pace.html
  images/pace.jpg
  javascript/pace.js
Labels: JWOC, medium

#123 Add a video of local installation in readme.md
  README.md
Labels: JWOC, hard

#132 Lean Body Mass Calculator Added
  css_files/leanmass.css
  html_files/fitnesstracking.html
  html_files/innnn.html
  html_files/leanmass.html
  images/lbm.png
  javascript/leanmass.js
Labels: JWOC, medium

#134 Footer updated in rateus page
  html_files/feedback.html
Labels: JWOC, easy

#137 Form[Feat] Adding Wellness Wave enrollment form #104
  enroll/Registration Form/index.html
  enroll/Registration Form/script.js
  enroll/Registration Form/style.css
  enroll/Registration Form/thankyou.html
  enroll/index.html
  enroll/style.css
  html_files/faq.html
  html_files/feedback.html
  html_files/fitnesstracking.html
  html_files/wellness.html
  index.html
Labels: JWOC, hard

#136 added reset button feature to all the calculators in tracking section
  css_files/sleep.css
  html_files/bmi.html
  html_files/bmr.html
  html_files/body_fat.html
  html_files/calorie.html
  html_files/dri.html
  html_files/due_date.html
  html_files/heart_rate.html
  html_files/pace.html
  html_files/prot_intake.html
  html_files/sleep.html
  html_files/water_intake.html
Labels: JWOC, medium

#150 Add Breast Cancer Risk Calculator
  css_files/breastcancer.css
  html_files/breastcancer.html
  html_files/fitnesstracking.html
  images/breastcancer.jpg
  javascript/breastcancer.js
Labels: JWOC, medium

#147 navbar style improved
  css_files/home.css
  css_files/navbar.css
  enroll/index.html
  html_files/faq.html
  html_files/feedback.html
  html_files/fitnesstracking.html
  html_files/wellness.html
  index.html
Labels: JWOC, medium
